# Generated by Django 4.2.3 on 2023-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateField(default='1900-01-01', verbose_name='出生日期'),
        ),
    ]
