# Generated by Django 4.2.3 on 2023-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_usermodel_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=15, verbose_name='密码'),
        ),
    ]
