# Generated by Django 3.2.4 on 2024-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='digest',
        ),
        migrations.AddField(
            model_name='file',
            name='file_save',
            field=models.FileField(default='uploads/', upload_to='uploads/'),
        ),
    ]
